### ISSUE TITLE
CSS breaks pym-shortcode

### ISSUE THREAD

**Issue by lajoiemedia** [INN/umbrella-cpipr#42]
In the CPIPR child theme's style.css is this bit of CSS:
```css
.iframe-youtube,
iframe {
  width: 100%;
  margin-top: 9px;
  height: 560px;
}
```
This CSS sets all iframes to 560px in height, everywhere. This obviously breaks the pym-shortcode responsive iframe plugin, and is a dangerous bit of CSS that will interfere with any plugins that rely on iframes.

There must be a more specific way to do whatever this CSS was intended to do.

I am working on a project that will rely on pym-shortcode heavily, so this is a major problem for me.
